stages:
  - build

.pages-build: &build
  image: ojob/pandoc-plantuml
  script:
    - cd src/
    - mkdir public/
    - mkdir plantuml-images/
    - pandoc --version
    # convert to slideshow, applying theme-specific afterwards (so with higher priority)
    - pandoc --filter pandoc-plantuml --defaults theme/pandoc-params.yml --self-contained *.md
    - mv public/ ../
  artifacts:
    paths:
      - public

test-pages:
  stage: build
  <<: *build
  except:
    - main

pages:
  stage: build
  <<: *build
  only:
    - main
