stages:
  - build

.pages-build: &build
  image: ghcr.io/astral-sh/uv:debian-slim
  script:
    - ./build.bash
    - cp -r archive/public/* public
  artifacts:
    paths:
      - public

test-pages:
  stage: build
  <<: *build
  except:
    - main

pages:
  stage: build
  <<: *build
  only:
    - main
